name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Run './manage-colima.sh start'
        2. Execute '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - macOS (Apple Silicon M1)
        - macOS (Apple Silicon M2)
        - macOS (Apple Silicon M3)
        - macOS (Apple Silicon M4)
        - macOS (Intel)
        - Linux (ARM64)
        - Linux (x86_64)
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Output of: uname -a"
      placeholder: "Darwin MacBook-Pro 25.0.0 Darwin Kernel Version 25.0.0"
    validations:
      required: true

  - type: input
    id: colima-version
    attributes:
      label: Colima Version
      description: "Output of: colima version"
      placeholder: "colima version 0.8.0"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      description: "Output of: docker --version"
      placeholder: "Docker version 27.0.3"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please provide relevant logs. Run one or more of:
        - ./manage-colima.sh logs [service-name]
        - docker compose logs [service-name]
        - colima logs
      render: shell
      placeholder: Paste logs here
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        If relevant, share your configuration (remove sensitive data):
        - .env file contents (sanitized)
        - docker-compose.yml modifications
        - Colima settings: colima list
      render: shell
      placeholder: Paste configuration here
    validations:
      required: false

  - type: dropdown
    id: affected-services
    attributes:
      label: Affected Services
      description: Which service(s) are affected?
      multiple: true
      options:
        - PostgreSQL
        - PgBouncer
        - MySQL
        - Redis Cluster
        - RabbitMQ
        - MongoDB
        - Forgejo (Git Server)
        - HashiCorp Vault
        - Prometheus
        - Grafana
        - Loki
        - Reference API (FastAPI)
        - Colima VM
        - Docker Compose
        - Management Script
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: Any additional information that might help
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included relevant logs and error messages
          required: true
        - label: I have provided steps to reproduce the issue
          required: true
        - label: I have sanitized any sensitive information from logs/config
          required: true
