name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - New Service Integration
        - Existing Service Enhancement
        - Management Script Improvement
        - Documentation Enhancement
        - Performance Optimization
        - Security Enhancement
        - Monitoring/Observability
        - Testing Infrastructure
        - Developer Experience
        - Configuration Management
        - Backup/Restore
        - Network Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Related Service (if applicable)
      description: Which service does this feature relate to?
      options:
        - PostgreSQL
        - PgBouncer
        - MySQL
        - Redis Cluster
        - RabbitMQ
        - MongoDB
        - Forgejo (Git Server)
        - HashiCorp Vault
        - Prometheus
        - Grafana
        - Loki
        - Reference API (FastAPI)
        - Colima VM
        - Management Script
        - Multiple Services
        - Not Service-Specific
        - Other

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: What other approaches have you thought about?
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: |
        - Developer Experience: ...
        - Performance: ...
        - Security: ...
        - Maintainability: ...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be valuable
      placeholder: |
        1. When setting up a new development environment...
        2. When debugging production issues...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Significantly improves productivity
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: Technical approach, configuration changes, dependencies needed, etc.
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Projects
      description: Are there similar implementations in other projects we can reference?
      placeholder: Links to similar features in other projects, documentation, etc.
    validations:
      required: false

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - No breaking changes expected
        - Minor breaking changes (with migration path)
        - Major breaking changes required
        - Unsure
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a PR to implement this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, diagrams, or information about the feature
      placeholder: Any additional information that might help
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues and PRs to avoid duplicates
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I have considered the impact on existing functionality
          required: true
