# Prometheus Configuration for Colima Services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'colima-dev'
    environment: 'development'

# Alertmanager configuration (optional, commented out for basic setup)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Rule files for alerts (optional)
# rule_files:
#   - 'alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI Reference Application
  - job_name: 'reference-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reference-api:8000']
    # Health check endpoint (for service discovery)
    # If FastAPI doesn't expose /metrics, we can use a custom exporter

  # Forgejo Git Server
  - job_name: 'forgejo'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['forgejo:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'forgejo'

  # Vector - Unified Observability Pipeline
  # Replaces: postgres-exporter, mongodb-exporter, node-exporter
  # Scrapes: redis-exporter (3x), cadvisor, rabbitmq
  - job_name: 'vector'
    static_configs:
      - targets: ['vector:9598']
    honor_labels: true  # Preserve labels from scraped metrics

  # PostgreSQL Exporter (REPLACED BY VECTOR - postgres-exporter container removed)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       replacement: 'postgres'

  # MySQL Exporter (DISABLED - container stopped due to critical bugs)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       replacement: 'mysql'

  # Redis Exporter (REPLACED BY VECTOR SCRAPING - exporters still running, Vector scrapes them)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets:
  #         - 'redis-exporter-1:9121'
  #         - 'redis-exporter-2:9121'
  #         - 'redis-exporter-3:9121'
  #       labels:
  #         cluster: 'redis-cluster'

  # RabbitMQ (REPLACED BY VECTOR SCRAPING - Vector scrapes built-in endpoint)
  # - job_name: 'rabbitmq'
  #   static_configs:
  #     - targets: ['rabbitmq:15692']

  # MongoDB Exporter (REPLACED BY VECTOR - mongodb-exporter container removed)
  # - job_name: 'mongodb'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']

  # Node Exporter (REPLACED BY VECTOR - node-exporter container removed)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # cAdvisor (REPLACED BY VECTOR SCRAPING - Vector scrapes cAdvisor)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # Vault metrics (if enabled)
  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    bearer_token: '${VAULT_TOKEN}'  # Will be substituted from environment
    static_configs:
      - targets: ['vault:8200']
    scheme: http
